POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Inl1bW8iLCJpZCI6IjVjZWZhZjc2NDkwMDUxNDVjNGZkZTA1NyIsImlhdCI6MTU1OTI4MTc5MX0.J0wWHJ2irt3KciMgesUJ1D6dv0WGK1Va9kd6-gY5pBw

{
    "title":"title6",
    "author":"author6",
    "url":"url6",
    "likes":12
}